questions =  [
    {"id": 0, "question": "Il carico di lavoro a casa dovrebbe essere aumentato così da determinare un’istruzione migliore negli studenti.", "effects": {"trad": 2}},
    {"id": 1, "question": "Le verifiche dovrebbero essere strutturate unicamente a domande chiuse", "effects": {"work": 1}},
    {"id": 2, "question": "Gli studenti dovrebbero poter accedere all'infrastruttura scolastica anche oltre gli orari di lezione per attuare dei loro progetti autogestiti.", "effects": {"gest": 2}},
    {"id": 3, "question": "la valutazione dovrebbe tenere in maggior considerazione l’impegno dello studente e non solo i risultati raggiunti.", "effects": {"trad": -2}},
    {"id": 4, "question": "Il voto, in quanto sistema di valutazione, è strumento efficace per valutare le abilità di uno studente durante il corso dell’anno scolastico.", "effects": {"trad": 2}},
    {"id": 5, "question": "Per il buon funzionamento della scuola è importante dare il giusto peso alle proposte degli studenti.", "effects": {"gest": 2}},
    {"id": 6, "question": "Ci vorrebbe una maggior coordinazione tra classe e insegnanti per la programmazione delle verifiche.", "effects": {"gest": 2}},
    {"id": 7, "question": "Dovrebbero essere introdotti degli elementi di autovalutazione da parte degli studenti.", "effects": {"gest": 2}},
    {"id": 8, "question": "È giusto che la soglia della sufficienza venga mantenuta al 60% per ogni tipo di verifica.", "effects": {"trad": 2}},
    {"id": 9, "question": "Le lezioni svolte nelle ore di educazione civica sono state utili alla preparazione personale come cittadino e componente della società.", "effects": {"trad": -2}},
    {"id": 11, "question": "Le uscite didattiche dovrebbero avere un collegamento più stretto con temi, luoghi e interessi emersi nel corso delle lezioni.", "effects": {"work": -2}},
    {"id": 12, "question": "L‘obiettivo prioritario dell’insegnante è quello di riuscire a concludere il programma a fine anno anche a costo di trattare superficialmente alcuni argomenti.", "effects": {"work": 2}},
    {"id": 13, "question": " Il tempo che a scuola viene dedicato ad argomenti di attualità è scarso e non viene sfruttato come sarebbe necessario.", "effects": {"work": -2}},
    {"id": 14, "question": "Gli insegnanti non sono in grado di creare collegamenti tra quanto insegnato e la complessità del mondo in cui viviamo.", "effects": {"trad": -2}},
    {"id": 15, "question": "La preparazione degli insegnanti sulle materie di loro competenza risulta adeguata.", "effects": {"trad": 1}},
    {"id": 16, "question": "Agli studenti dovrebbe essere fornita la possibilità di valutare i loro insegnanti.", "effects": {"gest": 2}},
    {"id": 17, "question": "La partecipazione studentesca alle scelte relative alla scuola dovrebbe essere maggiore.", "effects": {"gest": 2}},
    {"id": 18, "question": "Le lezioni dovrebbero svolgersi esclusivamente in modalità frontale.", "effects": {"trad": 2}},
    {"id": 19, "question": "I lavori di gruppo sono utili e dovrebbero essere parte integrante del lavoro svolto in classe.", "effects": {"trad": -2}},
    {"id": 20, "question": "Le ripetizioni tra pari (peer to peer) sono di grande utilità all’apprendimento e dovrebbero essere supportate dall’organizzazione scolastica.", "effects": {"gest": 2}},
    {"id": 21, "question": "La valutazione delle materie umanistiche dovrebbe focalizzarsi maggiormente sullo sviluppo delle capacità argomentative, in un confronto professore-studente, anziché essere affidata unicamente a test scritti.", "effects": {"trad": -2}},
    {"id": 22, "question": "Il voto di religione dovrebbe tornare a influire sulla media totale e quindi sui crediti ottenuti.", "effects": {"trad": 1}},
    {"id": 23, "question": "Il tempo dedicato al chiarimento di dubbi e/o alla correzione degli esercizi in classe è adeguato.", "effects": {"trad": 2}},
    {"id": 24, "question": "I docenti stimolano in maniera soddisfacente l’acquisizione di uno spirito critico.", "effects": {"work": 2}},
    {"id": 25, "question": "La valutazione dovrebbe incentrarsi di più sull’abilità nel problem solving rispetto all’utilizzo di metodi designati.", "effects": {"trad": -2}},
    {"id": 26, "question": "Si dovrebbero utilizzare molto di più le piattaforme online (come Classroom) per la condivisione di materiali didattici e per l’assegnazione di compiti.", "effects": {"trad": -2}},
    {"id": 27, "question": "Compiti e verifiche andrebbero sempre annotati sul registro.", "effects": {"trad": -2}},
    {"id": 28, "question": "Le L.I.M. in dotazione alla scuola sono adeguate.", "effects": {"trad": 1}},
    {"id": 29, "question": "La scuola è dotata di una connessione wi-fi soddisfacente.", "effects": {"trad": 1}},
    {"id": 30, "question": "In generale, gli investimenti della scuola in dotazioni informatiche appaiono congrui.", "effects": {"trad": 1}},
    {"id": 31, "question": "Le verifiche dovrebbero svolgersi unicamente su supporto cartaceo.", "effects": {"trad": 2}},
    {"id": 32, "question": "Per temi trattati e modalità di fruizione, i giornalini scolastici, già esistenti, risultano in generale interessanti per gli studenti.", "effects": {"gest": 2}},
    {"id": 33, "question": "Gli studenti sono sufficientemente liberi di esprimersi all’interno del sistema scolastico.", "effects": {"gest": -2}},
    {"id": 34, "question": "Gli studenti hanno la possibilità di contribuire alla scelta e allo sviluppo dei progetti che vengono svolti durante l’anno.", "effects": {"gest": -2}},
    {"id": 35, "question": "Le attività di studio organizzate durante la settimana scolastica (recuperi, corsi pomeridiani, ecc.) rispondono pienamente alle esigenze degli studenti", "effects": {"gest": 1}},
    {"id": 36, "question": "La scuola dovrebbe essere più aperta a incontri con persone esterne alla scuola per meglio motivare allo studio degli argomenti presenti nel programma..", "effects": {"trad": -2}},
    {"id": 37, "question": "L’insegnamento delle diverse materie proposte dovrebbe avvenire in un contesto di maggiore collaborazione interdisciplinare.", "effects": {"trad": -2}},
    {"id": 38, "question": "È accettabile che le valutazioni di alcuni test partano da 0.", "effects": {"trad": 1}},
    {"id": 39, "question": "È giusto che gli insegnanti pretendano l’utilizzo esclusivo del loro metodo di risoluzione dei problemi sanzionando negativamente ogni percorso alternativo.", "effects": {"trad": 2}},
    {"id": 40, "question": "Le giornate di cogestione sono utili alla didattica e alla crescita della persona.", "effects": {"gest": 2}},
    {"id": 41, "question": "La settimana di recupero è gestita dagli insegnanti nel migliore dei modi.", "effects": {"gest": -1}},
    {"id": 42, "question": "Il carico di lavoro viene di massima distribuito dagli insegnanti in modo equo nel corso dell’anno.", "effects": {"trad": 1}},
    {"id": 43, "question": "Il rapporto tra insegnante e studente è nella gran parte dei casi empatico", "effects": {"trad": 1}},
    {"id": 44, "question": "L’interazione studenti-professori durante le lezioni è insufficiente.", "effects": {"gest": -2}},
    {"id": 45, "question": "Specie con l’arrivo della bella stagione, si dovrebbero svolgere lezioni anche all’aperto.", "effects": {"trad": -2}},
    {"id": 46, "question": "Le macchinette automatiche presenti all’interno della scuola sono in numero sufficiente.", "effects": {"trad": 1}},
    {"id": 47, "question": "Dovrebbe esistere un bar nella scuola o all’interno del complesso di istituti, accessibile agli studenti.", "effects": {"gest": 1}},
    {"id": 48, "question": "I corsi e i laboratori extrascolastici attualmente disponibili sono sufficienti per permettere agli studenti di impiegare parte del loro tempo a fini scolastico-ricreativi", "effects": {"gest": -2}},
    {"id": 49, "question": "Gli studenti dovrebbero avere un tavolo di confronto immediato e permanente con le istituzioni.", "effects": {"gest": 2}},
    {"id": 50, "question": "Le attrezzature presenti nei laboratori non sono al passo coi tempi.", "effects": {"trad": 1}},
    {"id": 51, "question": "La frequenza di utilizzo dei laboratori da parte di tutte le classi è adeguata agli insegnamenti.", "effects": {"gest": -1}},
    {"id": 52, "question": "Il personale non docente dei collaboratori scolastici si dimostra collaborativo nello svolgimento delle sue funzioni.", "effects": {"trad": 1}},
    {"id": 53, "question": "Il personale scolastico amministrativo si pone con grande disponibilità verso i problemi degli studenti", "effects": {"trad": 2}},
    {"id": 54, "question": "La scuola dovrebbe fornire più occasione di socialità.", "effects": {"gest": 2}},
    {"id": 55, "question": "La Presidenza dovrebbe favorire la creazione di movimenti studenteschi.", "effects": {"work": -2}},
    {"id": 56, "question": "Le Assemblee di Istituto rappresentano un buon mezzo di confronto tra studenti..", "effects": {"gest": -2}},
    {"id": 57, "question": "La scuola dovrebbe avere più autonomia e dipendere meno da enti esterni, come la Provincia.", "effects": {"gest": 2}},
    {"id": 58, "question": "L’obbligo di frequenza a scuola non dovrebbe essere necessario.", "effects": {"work": 2}},
    {"id": 59, "question": "Sarebbe utile per il buon funzionamento della scuola ridurre il tasso corrente di ipocrisia e provare ad affrontare i problemi esistenti in termini di realtà.", "effects": {"trad": -2}}        
];